name: CI Student App
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    # je dis a github que mon projet est sur le sous dossier projet est dans le sous-dossier
    defaults:
      run:
        working-directory: ./App-Etudiants-Belgique
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build --if-present
