
name: CI Student App
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install and Build
        # On combine le "cd" et le "npm install" sur la même ligne
        run: |
          cd App-Etudiants-Belgique
          npm install
          npm run build --if-present  
